name: english_for_it
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.4.0  
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.0.1
  go_router: ^4.0.0
  google_fonts: ^3.0.1  
  injectable: ^1.5.3
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1
  text_to_speech: ^0.2.3

dev_dependencies:
  bdd_widget_test: ^1.4.1
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  injectable_generator: ^1.5.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/dictionary.db

